# Cendre hard palette, adapted for Omarchy. https://cendretheme.com/
mode = "dark"
accent = "#ea9875"
selection = "#2f1e17"
selection_background = "#2f1e17"
selection_foreground = "#e6d5c2"
muted = "#73665b"
background = "#171311"
dark_background = "#0f0c0a"
darker_background = "#0f0c0a"
lighter_background = "#201b19"
foreground = "#e6d5c2"
dark_foreground = "#73665b"
light_foreground = "#a09384"
bright_foreground = "#e6d5c2"
red = "#d1766e"
yellow = "#fcba81"
orange = "#ea9875"
green = "#99af6b"
cyan = "#4e89a2"
blue = "#58bdff"
magenta = "#9480ba"
brown = "#5a504c"
bright_red = "#d25780"
bright_yellow = "#f4a21c"
bright_green = "#43b16a"
bright_cyan = "#20c9cb"
bright_blue = "#8bcfff"
bright_magenta = "#a692cd"
hyprland_active_border = "#ea9875 #fcba81 45deg"
hyprland_inactive_border = "#362f2c"
