[Icon Theme]
Name=Cendre
Comment=Copper and ash folders, adapted from Yaru
Inherits=Yaru,Adwaita,hicolor
Example=folder
Directories=16x16/places,16x16@2x/places,24x24/places,24x24@2x/places,32x32/places,32x32@2x/places,48x48/places,48x48@2x/places,256x256/places,256x256@2x/places

[16x16/places]
Size=16
Scale=1
Context=Places
Type=Fixed

[16x16@2x/places]
Size=16
Scale=2
Context=Places
Type=Fixed

[24x24/places]
Size=24
Scale=1
Context=Places
Type=Fixed

[24x24@2x/places]
Size=24
Scale=2
Context=Places
Type=Fixed

[32x32/places]
Size=32
Scale=1
Context=Places
Type=Fixed

[32x32@2x/places]
Size=32
Scale=2
Context=Places
Type=Fixed

[48x48/places]
Size=48
Scale=1
Context=Places
Type=Fixed

[48x48@2x/places]
Size=48
Scale=2
Context=Places
Type=Fixed

[256x256/places]
Size=256
Scale=1
Context=Places
Type=Fixed

[256x256@2x/places]
Size=256
Scale=2
Context=Places
Type=Fixed
